version: '3.0'
services:
  # apicurio:
  #   image: apicurio/apicurio-registry-mem:2.0.0.Final
  #   container_name: apicurio
  #   ports:
  #    - 8080:8080
  mysql:
    image: debezium/example-mysql:1.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw 
    volumes:
      - ./data/db:/var/lib/mysql
  nifi:
    image: apache/nifi:1.12.0
    container_name: nifi
    ports:
      - "8180:8180"
      - "8443:8443"
    links:  
      - mysql
    environment:
      - NIFI_WEB_HTTP_PORT=8180
    volumes:
      - ./nifi_state:/opt/nifi/nifi-current/state
      - ./nifi_db:/opt/nifi/nifi-current/database_repository
      - ./nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - ./nifi_content:/opt/nifi/nifi-current/content_repository
      - ./nifi_provenance:/opt/nifi/nifi-current/provenance_repository  
  connect:
    image: debezium/connect:latest
    container_name: connect
    ports:
      - 8083:8083
    links:
      - mysql
      # - apicurio
    environment:
      - BOOTSTRAP_SERVERS=my servers
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - CONFIG_STORAGE_REPLICATION_FACTOR=3
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - OFFSET_STORAGE_REPLICATION_FACTOR=3
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - STATUS_STORAGE_REPLICATION_FACTOR=3
      # - ENABLE_APICURIO_CONVERTERS=true
  superset:
    image: apache/superset:latest
    container_name: superset
    environment:
      - ROW_LIMIT = 5000
      - SUPERSET_WEBSERVER_PORT=9088
      - MAPBOX_API_KEY = 'my key'
    ports:
      - "9088:9088"