apiVersion: v1
kind: Pod
metadata:
  name: kafka-connect
  namespace: prod
spec:
  containers:
  - name: kafka-connect
    image: debezium/connect:1.5
    ports:
      - name: kafka-connect
        containerPort: 8083
        protocol: TCP
    env:
      - name: GROUP_ID
        value: "1"
      - name: CONFIG_STORAGE_TOPIC
        value: my_connect_configs
      - name: OFFSET_STORAGE_TOPIC
        value: my_connect_offsets
      - name: STATUS_STORAGE_TOPIC
        value: my_connect_statuses
