apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: prod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: debezium/example-mysql:1.5
    ports:
      - name: web
        containerPort: 3306
        protocol: TCP
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: debezium
      - name: MYSQL_USER
        value: mysqluser
      - name: MYSQL_PASSWORD
        value: mysqlpw
