apiVersion: v1
kind: Pod
metadata:
  name: nifi 
  namespace: prod
  labels:
    app: nifi
spec:
  containers:
  - name: nifi
    image: apache/nifi:1.13.2
    ports:
      - name: nifi
        containerPort: 8080
        protocol: TCP
